### ISSUE TITLE
Compile python bindings fails - Not implemented size of fixed edge

### ISSUE THREAD

**Issue by henrikmidtiby** [RainerKuemmerle/g2o#926]
I have tried to compile the python bindings for g2o, but I get stuck on a compile error in the process when I try to do so.

I get the following error
```
Consolidate compiler generated dependencies of target g2opy
[ 92%] Building CXX object python/CMakeFiles/g2opy.dir/types/icp/py_types_icp.cpp.o
In file included from /home/hemi/Desktop/g2o-tests/g2o-test/python/types/icp/py_types_icp.h:3,
                 from /home/hemi/Desktop/g2o-tests/g2o-test/python/types/icp/py_types_icp.cpp:1:
/home/hemi/Desktop/g2o-tests/g2o-test/python/detail/registry.h: In member function ‘auto g2o::detail::Registry::registerEdgeFixed(const char*)’:
/home/hemi/Desktop/g2o-tests/g2o-test/python/detail/registry.h:68:21: error: static assertion failed: Not implemented size of fixed edge
   68 |       static_assert(false, "Not implemented size of fixed edge");
      |                     ^~~~~
make[2]: *** [python/CMakeFiles/g2opy.dir/build.make:286: python/CMakeFiles/g2opy.dir/types/icp/py_types_icp.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3149: python/CMakeFiles/g2opy.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

I can reproduce the error through the following steps.

```
git clone git@github.com:RainerKuemmerle/g2o.git g2o-test
cd g2o-test/
git checkout pymem
mkdir build
cd build
cmake .. -DG2O_BUILD_PYTHON=ON
make
```

The error occurs in this version commit 70f058fde451650 dated 2025-09-21 17:24.

When I go back through the commit history, the error seems to be introduced in d4d4f50fb1287 dated 2025-04-13 20:14.
