### ISSUE TITLE
g2o doesn't compile with eigen version > 3.3.x

### ISSUE THREAD

**Issue by zhangxaochen** [RainerKuemmerle/g2o#143]
I've been trying to build g2o with eigen, on windows + msvc2010,
1. I tried eigen3.0.1, found g2o needs eigen version >=3.1 to have `solver_eigen` generated;
2. then I downloaded the latest eigen release 3.3.1, and the trunk 3.3.90, both encountered errors:

`Error    1    error LNK2019: unresolved external symbol "__declspec(dllimport) public: class Eigen::Map<class Eigen::Matrix<double,6,6,0,6,6>,0,class Eigen::Stride<0,0> > & __thiscall g2o::BaseVertex<6,class Eigen::Transform<double,3,1,0> >::A(void)" (__imp_?A@?$BaseVertex@$05V?$Transform@N$02$00$0A@@Eigen@@@g2o@@QAEAAV?$Map@V?$Matrix@N$05$05$0A@$05$05@Eigen@@$0A@V?$Stride@$0A@$0A@@2@@Eigen@@XZ) referenced in function "public: virtual void __thiscall g2o::BaseBinaryEdge<3,class g2o::EdgeGICP,class g2o::VertexSE3,class g2o::VertexSE3>::constructQuadraticForm(void)" (?constructQuadraticForm@?$BaseBinaryEdge@$02VEdgeGICP@g2o@@VVertexSE3@2@V32@@g2o@@UAEXXZ)    E:\Github\g2o\_build.vc10.x86\g2o\types\icp\types_icp.obj`

and even more strange:
```
1>..\..\..\..\g2o\examples\calibration_odom_laser\sclam_laser_calib.cpp(284909182): fatal error C1001: An internal error has occurred in the compiler.
1>  (compiler file 'msc1.cpp', line 1420)
```

3. then I had to try eigen 3.2.10 (newest before 3.3), and succeeded. 

So is it because some flaws in eigen or g2o?

**Comment by mikepurvis** [comment]
Which version of G2O are you using? Several fixes for Eigen 3.3+ have merged in recent months but are not yet part of a G2O tagged release:

https://github.com/RainerKuemmerle/g2o/search?q=eigen&type=Commits

**Comment by RainerKuemmerle** [comment]
Since I'm not an active user of Windows, I decided to put up a CI for Windows.
Using VS 2015 and Eigen 3.3 with the current master, all seems to be fine.
