### ISSUE TITLE
g2o issues with ROS2 humble .

### ISSUE THREAD

**Issue by chrissunny94** [RainerKuemmerle/g2o#742]
```
undefined reference to symbol '_ZN3fmt2v86detail18throw_format_errorEPKc'
/usr/bin/ld: /lib/x86_64-linux-gnu/libfmt.so.8: error adding symbols: DSO missing from command line
```

1. Ubuntu 22.04
2. ROS humble 

Not sure if its exactly a ROS problem or something else .

But tracking it .

https://github.com/wh200720041/floam/pull/57

**Comment by RainerKuemmerle** [comment]
When are you getting this linker error? When you compile g2o or when you link your code with g2o?

**Comment by chrissunny94** [comment]
While linking with g2o .
Getting it with the following .
https://github.com/Chris7462/floam/tree/g2o


Same code worked with ROS2 FOXY on Ubuntu 20.04 .

I have insalled g2o from the ROS2 release , `sudo apt install ros-<distro>-libg2o` , i am not sure of the corresponding g2o release with the same .

I will trying installing the **FOXY-bundled-g2o** from source and revert back for further clarity .

**Comment by RainerKuemmerle** [comment]
I am not following the ROS2 releases in detail. But I assume a different release is used as the dependency to fmt/spdlog is rather new.How is linking performed? Are you using the target files exported by cmake. In ROS1 noetic this is tedious but prevents issues. Not sure about ROS2 again.Am 22.11.2023 um 05:50 schrieb Chrissunny94 ***@***.***>:﻿
While linking with g2o .
Getting it with the following .
https://github.com/Chris7462/floam/tree/g2o
Same code worked with ROS2 FOXY on Ubuntu 20.04 .
I have insalled g2o from the ROS2 release , sudo apt install ros-<distro>-libg2o , i am not sure of the corresponding g2o release with the same .
I will trying installing the FOXY-bundled-g2o from source and revert back for further clarity .

**Comment by chrissunny94** [comment]
Noted! 

I will try to dig in over this weekend .

Thank you
